sampling_rate: 44100
num_channels: 2
n_mels: 160
n_fft: 4096
window_length: 4096
hop_length: 1024

hidden_sizes: [16, 32, 64, 128]
dual_path_blocks: [3, 3, 3, 3]
down_sampling_factors: [[2, 2], [2, 2], [2, 2], [2, 2]]
num_time_transformer: 1
num_freq_transformer: 1
use_mix_ln: false
num_genres: 1496

##############################################################
# training
##############################################################
initial_step: 0
epochs: 200
batch_size: 4
accum_steps: 32
patch_len: 1323000 # 44100 * 30.0
cache_size: 250
log_dir: ./logs/
dataset_folder_path: "./Dataset/Processed"
model_save_freq: 10000
epoch_max_steps: null
